require_relative '../node_modules/react-native/scripts/react_native_pods'

platform :ios, '16.4'

pre_install do |installer|
  # Patch generated podspecs to use iOS 13.4
  generated_podspecs = Dir.glob('build/generated/ios/*.podspec')
  generated_podspecs.each do |podspec_path|
    if File.exist?(podspec_path)
      content = File.read(podspec_path)
      # Replace any deployment target with 13.4
      content.gsub!(/s\.ios\.deployment_target\s*=\s*['"][^'"]*['"]/, "s.ios.deployment_target = '13.4'")
      content.gsub!(/spec\.ios\.deployment_target\s*=\s*['"][^'"]*['"]/, "spec.ios.deployment_target = '13.4'")
      File.write(podspec_path, content)
      puts "Patched deployment target in #{podspec_path} to iOS 13.4"
    end
  end
end

target 'EduConnect' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => false,
    :new_arch_enabled => false
  )

  post_install do |installer|
    react_native_post_install(installer)
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
      end
    end

    # Ensure codegen pods also honor the deployment target
    installer.pod_targets.each do |pod|
      if ['ReactAppDependencyProvider','ReactCodegen'].include?(pod.name)
        pod.xcconfigs.each do |config_name, cfg|
          cfg['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
        end
        pod.build_settings.each do |config_name, settings|
          settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
        end
      end
    end
  end
end
