name: Build iOS App (Simple)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-14
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
    
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
    
      - name: Install dependencies
        run: npm install
        
      - name: Install CocoaPods
        run: |
          gem install cocoapods
          pod --version
        
      - name: Pod Install
        run: |
          cd ios
          pod install --repo-update
        
      - name: Build iOS Archive
        run: |
          cd ios
          xcodebuild archive \
            -workspace EduConnect.xcworkspace \
            -scheme EduConnect \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath ./build/EduConnect.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            DEVELOPMENT_TEAM=""
    
      - name: Upload iOS Archive
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: ios-archive-simple
          path: ios/build/EduConnect.xcarchive
          retention-days: 7