name: iOS Nuclear Build

on:
  push:
    branches: [ main ]

jobs:
  build-ios:
    runs-on: macos-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Install CocoaPods
        run: gem install cocoapods
        
      - name: Pod Install
        run: |
          cd ios
          pod install
        
      - name: Build Archive
        run: |
          cd ios
          xcodebuild archive \
            -workspace EduConnect.xcworkspace \
            -scheme EduConnect \
            -configuration Release \
            -destination generic/platform=iOS \
            -archivePath ./EduConnect.xcarchive \
            CODE_SIGNING_ALLOWED=NO
    
      - name: Upload Archive
        uses: actions/upload-artifact@v4
        with:
          name: ios-nuclear-build
          path: ios/EduConnect.xcarchive